Repository andela/vali-ah-backend, pull requests merged in 2019-08, with the labels that each got.

#24 #167650368: Fix npm start error in production
  .babelrc
  package-lock.json
  package.json
Labels: ready-for-review

#17 #167377536: Signup validation middleware
  .gitignore
  docs/swagger.json
  package-lock.json
  package.json
  src/middlewares/validator.js
  src/routes/auth.js
  src/routes/index.js
  src/swagger.js
  src/validations/auth.js
  tests/auth.test.js
  tests/fixtures/users.js
  tests/test.js
Labels: feedback-implemented

#21 #167377545 API endpoint to create comment for an article
  .babelrc
  .eslintrc
  .gitignore
  .nycrc
  config/db/seeders/20190731032821-articles.js
  config/db/seeders/20190731032821-user-article.js
  config/db/seeders/20190731032821-users.js
  docs/swagger.json
  package-lock.json
  package.json
  src/controllers/article.js
  src/controllers/auth.js
  src/helpers/auth.js
  src/helpers/errors.js
  src/index.js
  src/middlewares/asyncWrapper.js
  src/middlewares/errorHandler.js
  src/middlewares/validator.js
  src/models/ArticleCategories.js
  src/models/Articles.js
  src/models/BlacklistedTokens.js
  src/models/Bookmarks.js
  src/models/Categories.js
  src/models/Comments.js
  src/models/Followers.js
  src/models/Notifications.js
  src/models/ReadStats.js
  src/models/Reports.js
  src/models/Roles.js
  src/models/Users.js
  src/models/Votes.js
  src/models/index.js
  src/routes/article.js
  src/routes/auth.js
  src/routes/index.js
  src/sequelize.js
  src/services/notification.js
  src/validations/auth.js
  src/validations/comment.js
  tests/auth.test.js
  tests/fixtures/articles.js
  tests/fixtures/users.js
  tests/helpers/errors.test.js
  tests/helpers/index.js
  tests/middlewares/asyncWrapper.test.js
  tests/middlewares/errorHandler.test.js
  tests/middlewares/index.js
  tests/models/articles.test.js
  tests/models/index.js
  tests/routes/articles.test.js
  tests/routes/auth.test.js
  tests/routes/index.js
  tests/services/email.test.js
  tests/services/index.js
  tests/services/notification.test.js
  tests/test.js
Labels: ready-for-review

#23 #167377539 Enable social login
  .env.example
  .nycrc
  config/db/migrations/20190728220710-create-users.js
  docs/swagger.json
  package-lock.json
  package.json
  src/controllers/auth.js
  src/index.js
  src/routes/auth.js
  src/routes/index.js
  src/services/auth.js
  src/validations/auth.js
  tests/fixtures/auth.js
  tests/routes/index.js
  tests/routes/socialAuth.test.js
Labels: feedback-implemented

#22 #167377537 Implement user signout endpoint
  .env.example
  config/db/migrations/20190728220710-create-users.js
  docs/swagger.json
  package.json
  src/controllers/article.js
  src/controllers/auth.js
  src/helpers/auth.js
  src/middlewares/asyncWrapper.js
  src/middlewares/authentication.js
  src/middlewares/validator.js
  src/models/Articles.js
  src/models/Users.js
  src/routes/article.js
  src/routes/auth.js
  src/services/auth.js
  src/swagger.js
  src/validations/auth.js
  src/validations/comment.js
  tests/fixtures/users.js
  tests/middlewares/asyncWrapper.test.js
  tests/middlewares/authentication.test.js
  tests/middlewares/index.js
  tests/routes/articles.test.js
  tests/routes/auth.test.js
  tests/routes/socialAuth.test.js
Labels: feedback-implemented, ready-for-review

#28 167377549 Create user notification system
  .env.example
  config/db/migrations/20190728220710-create-users.js
  config/db/migrations/20190728221239-create-notifications.js
  config/db/migrations/20190806155039-create-session.js
  package-lock.json
  package.json
  src/helpers/models.js
  src/helpers/socket.js
  src/index.js
  src/models/Articles.js
  src/models/Notifications.js
  src/models/Sessions.js
  src/models/Users.js
  src/models/index.js
  src/services/cron.js
  src/services/email.js
  src/services/notification.js
  src/socket.js
  tests/fixtures/session.js
  tests/fixtures/users.js
  tests/helpers/index.js
  tests/helpers/socket.test.js
  tests/models/articles.test.js
  tests/models/index.js
  tests/models/notifications.test.js
  tests/models/sessions.test.js
  tests/models/users.test.js
  tests/routes/socialAuth.test.js
  tests/services/notification.test.js
Labels: ready-for-review

#30 #167377552 Pagination support for articles
  package-lock.json
  src/controllers/article.js
  src/helpers/paginator.js
  src/routes/article.js
  src/validations/pagination.js
  tests/routes/index.js
  tests/routes/pagination.test.js
Labels: feedback-implemented

#27 #167377557 Implement bookmark article functionality
  .env.example
  config/db/seeders/20190731032821-articles.js
  docs/swagger.json
  package.json
  src/controllers/article.js
  src/helpers/errors.js
  src/models/Articles.js
  src/models/Bookmarks.js
  src/routes/article.js
  src/validations/bookmark.js
  tests/routes/articles.test.js
  tests/routes/bookmarks.test.js
  tests/routes/index.js
Labels: ready-for-review

#26 #167377540 User can update and view profile
  .env.example
  app.json
  docs/swagger.json
  src/controllers/user.js
  src/helpers/index.js
  src/helpers/makeCapitalize.js
  src/middlewares/emptyBodyValidator.js
  src/middlewares/index.js
  src/routes/index.js
  src/routes/user.js
  src/validations/auth.js
  src/validations/profileSchema.js
  tests/fixtures/articles.js
  tests/fixtures/users.js
  tests/routes/index.js
  tests/routes/profile.test.js
Labels: feedback-implemented

#29 #167377554 Search functionality for articles
  config/db/migrations/20190728220750-create-articleCategories.js
  config/db/seeders/20190731032821-articles.js
  docs/swagger.json
  package-lock.json
  src/controllers/article.js
  src/controllers/auth.js
  src/helpers/genericArticleHelper.js
  src/helpers/index.js
  src/helpers/paginator.js
  src/models/ArticleCategories.js
  src/models/Articles.js
  src/models/Users.js
  src/routes/article.js
  src/services/notification.js
  src/validations/auth.js
  src/validations/pagination.js
  tests/fixtures/articles.js
  tests/fixtures/users.js
  tests/routes/articles.test.js
  tests/routes/pagination.test.js
Labels: peer-review

#31 #167377547 Users can upvote and downvote articles
  .env.example
  docs/swagger.json
  src/controllers/article.js
  src/middlewares/authentication.js
  src/middlewares/errorHandler.js
  src/models/Articles.js
  src/models/Votes.js
  src/routes/article.js
  src/validations/articles.js
  tests/fixtures/articles.js
  tests/fixtures/users.js
  tests/routes/articles.test.js
  tests/routes/bookmarks.test.js
  tests/routes/pagination.test.js
Labels: peer-review

#33 #167588625 User can get comments for an article
  .env.example
  docs/swagger.json
  src/controllers/article.js
  src/helpers/errors.js
  src/middlewares/errorHandler.js
  src/routes/article.js
  src/validations/comment.js
  tests/fixtures/comments.js
  tests/routes/articles.test.js
Labels: peer-review

#32 #167377541 Users should be able to CRUD articles
  .env.example
  app.json
  config/db/migrations/20190728220728-create-articles.js
  config/db/migrations/20190728220750-create-articleCategories.js
  config/db/seeders/20190802071800-demo-category.js
  config/db/seeders/20190809172230-demo-votes.js
  docs/swagger.json
  package-lock.json
  package.json
  src/controllers/article.js
  src/helpers/article.js
  src/helpers/genericArticleHelper.js
  src/middlewares/articles.js
  src/middlewares/asyncWrapper.js
  src/middlewares/authentication.js
  src/models/ArticleCategories.js
  src/models/Articles.js
  src/models/Categories.js
  src/routes/article.js
  src/services/imageUpload.js
  src/swagger.js
  src/validations/article.js
  tests/fixtures/articles.js
  tests/fixtures/users.js
  tests/models/articles.test.js
  tests/models/notifications.test.js
  tests/models/sessions.test.js
  tests/models/users.test.js
  tests/routes/articles.test.js
  tests/routes/pagination.test.js
  tests/services/notification.test.js
Labels: ready-for-review

#25 #167377538 Users should be able to reset and update their password
  .env.example
  config/db/seeders/20190731032821-users.js
  docs/swagger.json
  package-lock.json
  package.json
  src/controllers/auth.js
  src/models/Users.js
  src/routes/auth.js
  src/services/email.js
  src/services/notification.js
  src/validations/auth.js
  tests/fixtures/articles.js
  tests/fixtures/users.js
  tests/routes/articles.test.js
  tests/routes/index.js
  tests/routes/resetPassword.test.js
  tests/services/notification.test.js
Labels: peer-review

#36 #167377559 Users can upvote and downvote comments
  .env.example
  config/db/migrations/20190813125838-create-comment-votes.js
  config/db/seeders/20190731032821-articles.js
  docs/swagger.json
  src/controllers/article.js
  src/controllers/comment.js
  src/models/CommentVotes.js
  src/models/Comments.js
  src/models/Users.js
  src/routes/article.js
  src/routes/comment.js
  src/routes/index.js
  src/validations/articles.js
  src/validations/comment.js
  tests/fixtures/articles.js
  tests/fixtures/comments.js
  tests/routes/comments.test.js
  tests/routes/index.js
Labels: peer-review

#39 #167377553 Users can view all authors
  .env.example
  docs/swagger.json
  src/controllers/author.js
  src/helpers/models.js
  src/routes/author.js
  src/routes/index.js
  tests/routes/getAllAuthors.test.js
  tests/routes/index.js
Labels: ready-for-review

#35 #167377548 Implement follow, unfollow, get all followers and all followings of a user
  .env.example
  config/db/migrations/20190728221209-create-followers.js
  docs/swagger.json
  src/controllers/article.js
  src/controllers/auth.js
  src/controllers/user.js
  src/helpers/genericArticleHelper.js
  src/helpers/index.js
  src/helpers/makeCapitalize.js
  src/helpers/models.js
  src/helpers/paginator.js
  src/helpers/socket.js
  src/middlewares/asyncWrapper.js
  src/middlewares/authentication.js
  src/middlewares/emptyBodyValidator.js
  src/middlewares/errorHandler.js
  src/models/ArticleCategories.js
  src/models/Articles.js
  src/models/Bookmarks.js
  src/models/Followers.js
  src/models/Users.js
  src/routes/user.js
  src/services/auth.js
  src/services/email.js
  src/services/notification.js
  src/validations/profileSchema.js
  tests/fixtures/users.js
  tests/models/users.test.js
  tests/routes/articles.test.js
  tests/routes/profile.test.js
Labels: feedback-implemented

#34 #167377564 Users should be able to highlight and comment on any text in an article
  config/db/migrations/20190728221000-create-inlineComments.js
  docs/swagger.json
  src/controllers/article.js
  src/helpers/cosine.js
  src/middlewares/authentication.js
  src/models/Articles.js
  src/models/InlineComments.js
  src/models/Users.js
  src/routes/article.js
  src/services/cron.js
  src/validations/articles.js
  src/validations/comment.js
  tests/fixtures/articles.js
  tests/fixtures/comments.js
  tests/fixtures/users.js
  tests/helpers/cosine.test.js
  tests/helpers/index.js
  tests/models/articles.test.js
  tests/routes/articles.test.js
  tests/routes/auth.test.js
Labels: ready-for-review

#37 #167510760 Implement route to get articles of authors a user follows
  config/db/seeders/20190813191315-demo-follower-table.js
  docs/swagger.json
  src/controllers/article.js
  src/controllers/auth.js
  src/models/Articles.js
  src/models/Categories.js
  src/models/Followers.js
  src/models/Users.js
  src/routes/article.js
  src/validations/article.js
  tests/fixtures/articles.js
  tests/routes/articles.test.js
  tests/routes/resetPassword.test.js
Labels: ready-for-review

#40 #167512374 User can get article category subscribed for
  .env.example
  config/db/migrations/20190728220752-create-subscriptions.js
  config/db/seeders/20190731032821-articles.js
  docs/swagger.json
  src/controllers/article.js
  src/controllers/author.js
  src/controllers/user.js
  src/helpers/auth.js
  src/middlewares/authentication.js
  src/models/Articles.js
  src/models/Categories.js
  src/models/Subscriptions.js
  src/models/Users.js
  src/routes/article.js
  src/routes/author.js
  src/services/notification.js
  src/validations/article.js
  src/validations/articles.js
  src/validations/auth.js
  tests/fixtures/articles.js
  tests/fixtures/subscriptions.js
  tests/fixtures/users.js
  tests/models/users.test.js
  tests/routes/articles.test.js
  tests/routes/profile.test.js
Labels: implementing-feedback

#41 #167972588 Catch error thrown for unique userName during signup
  src/controllers/auth.js
  src/models/Users.js
  tests/fixtures/users.js
  tests/routes/auth.test.js
Labels: ready-for-review

#42 #168054742 Fix inline comments normalisation and response message
  docs/swagger.json
  src/controllers/article.js
  src/helpers/cosine.js
  src/models/Articles.js
  src/routes/article.js
Labels: feedback-implemented

#47 #168055387 Fix page and limit validation on users can view all authors route
  src/controllers/author.js
  src/routes/author.js
  src/validations/paginator.js
  tests/routes/bookmarks.test.js
  tests/routes/resetPassword.test.js
Labels: peer-review

#43 #168055703 Fix paginator count response
  src/controllers/article.js
  src/helpers/paginator.js
  tests/routes/articles.test.js
  tests/routes/getAllAuthors.test.js
  tests/routes/pagination.test.js
Labels: feedback-implemented

#44 #167969811 Users can subscribe to articles
  config/db/seeders/20190802071800-demo-category.js
  docs/swagger.json
  src/controllers/user.js
  src/helpers/subscription.js
  src/models/Users.js
  src/routes/user.js
  src/validations/profileSchema.js
  tests/fixtures/subscriptions.js
  tests/routes/profile.test.js
Labels: peer-review

#48 #168054239 Fix slug bug associated with the CRUD articles feature
  config/db/migrations/20190728220728-create-articles.js
  package-lock.json
  package.json
  src/controllers/article.js
  src/helpers/slugify.js
  src/middlewares/articles.js
  src/middlewares/authentication.js
  src/models/ArticleCategories.js
  src/models/Articles.js
  src/routes/article.js
  src/validations/article.js
  tests/fixtures/articles.js
  tests/fixtures/users.js
  tests/models/articles.test.js
  tests/routes/articles.test.js
Labels: peer-review

#49 #168058121 User gets all bookmarks
  docs/swagger.json
  src/controllers/article.js
  src/controllers/auth.js
  src/controllers/author.js
  src/controllers/comment.js
  src/controllers/user.js
  src/helpers/article.js
  src/helpers/genericArticleHelper.js
  src/helpers/index.js
  src/helpers/isEmptyObject.js
  src/helpers/paginator.js
  src/middlewares/emptyBodyValidator.js
  src/middlewares/index.js
  src/middlewares/validator.js
  src/models/Users.js
  src/routes/article.js
  src/routes/user.js
  src/validations/article.js
  src/validations/paginator.js
  src/validations/profile.js
  tests/models/users.test.js
  tests/routes/articles.test.js
  tests/routes/bookmarks.test.js
  tests/routes/comments.test.js
  tests/routes/pagination.test.js
  tests/routes/profile.test.js
  tests/routes/resetPassword.test.js
Labels: feedback-implemented

#45 #168064097 Fix tag content and response message
  docs/swagger.json
  src/controllers/article.js
  src/controllers/user.js
  src/helpers/article.js
  src/helpers/index.js
  src/helpers/makeCapitalize.js
  src/helpers/models.js
  src/helpers/paginator.js
  src/models/Users.js
  src/routes/user.js
  src/validations/auth.js
  src/validations/profile.js
  tests/fixtures/articles.js
  tests/fixtures/users.js
  tests/middlewares/asyncWrapper.test.js
  tests/routes/articles.test.js
  tests/routes/profile.test.js
  tests/services/notification.test.js
Labels: feedback-implemented

#50 #168095164 Fix password reset link sent to user email
  .env.example
  app.json
  src/controllers/auth.js
  src/services/email.js
  src/services/notification.js
  tests/routes/bookmarks.test.js
  tests/routes/getAllAuthors.test.js
Labels: peer-review

#46 #168059057 Fix the comment object to return net vote count
  src/controllers/article.js
  src/controllers/comment.js
  src/helpers/article.js
  tests/fixtures/comments.js
  tests/routes/articles.test.js
Labels: feedback-implemented
