Repository andela/vali-ah-backend, pull requests merged in 2019-07, with the labels that each got.

#1 #167377527 Setup Eslint
  .eslintrc
  package-lock.json
  package.json
Labels: ready-for-review

#7 #167377528 Integrate HoundCI with badge attached to README
  .hound.yml
  README.md
Labels: ready-for-review

#4 #167439730 Setup Babel
  .babelrc
  .eslintignore
  .gitignore
  package-lock.json
  package.json
  src/config/index.js
  src/config/passport.js
  src/index.js
  src/models/User.js
  src/routes/api/index.js
  src/routes/api/users.js
  src/routes/index.js
Labels: feedback-implemented

#6 #167377524 Setup Travis CI with Badges
  .env.example
  .github/commit_message_template.md
  .github/pull_request_template.md
  .gitignore
  .travis.yml
  README.md
  package-lock.json
  package.json
  tests/test.js
Labels: feedback-implemented

#5 #167377529 Deploy application to Heruko
  .gitignore
  src/config/passport.js
  src/models/User.js
  src/routes/api/index.js
  src/routes/api/users.js
Labels: ready-for-review

#8 #167452886 Refactor server and folder structure
  .env.example
  package-lock.json
  package.json
  src/config/index.js
  src/index.js
  src/routes/index.js
Labels: in-review

#3 #167377525 Setup sequelize database
  .env.example
  .sequelizerc
  config/migrations/20190723163335-create-user.js
  config/sequelize.js
  package-lock.json
  package.json
  src/models/index.js
  src/models/user.js
Labels: feedback-implemented

#10 #167377532 Setup swagger documentation
  .env.example
  docs/swagger.json
  package-lock.json
  package.json
  src/index.js
  src/swagger.js
Labels: feedback-implemented

#13 #167503053 Setup Review Apps on Heroku
  app.json
Labels: feedback-implemented, ready-for-review

#12 #167377530 Setup unit testing
  .nycrc
  package-lock.json
  package.json
  src/index.js
  src/middlewares/errorHandler.js
  tests/app.test.js
  tests/fake.test.js
  tests/middleware.test.js
  tests/test.js
Labels: feedback-implemented

#14 #167377535 Email notification for User verification
  .babelrc
  .env.example
  .nycrc
  package-lock.json
  package.json
  src/services/email.js
  src/services/notification.js
  tests/services/email.test.js
  tests/services/notification.test.js
  tests/test.js
Labels: feedback-implemented

#16 #167510280 Create database schema
  .sequelizerc
  README.md
  config/db/migrations/20190728220710-create-user.js
  config/db/migrations/20190728220728-create-article.js
  config/db/migrations/20190728220750-create-articleCategory.js
  config/db/migrations/20190728220837-create-author.js
  config/db/migrations/20190728220928-create-bookmark.js
  config/db/migrations/20190728220944-create-category.js
  config/db/migrations/20190728221000-create-comments.js
  config/db/migrations/20190728221040-create-downvote.js
  config/db/migrations/20190728221104-create-upvote.js
  config/db/migrations/20190728221209-create-followers.js
  config/db/migrations/20190728221239-create-notification.js
  config/db/migrations/20190728221313-create-permissions.js
  config/db/migrations/20190728221340-create-readStat.js
  config/db/migrations/20190728221410-create-report.js
  config/db/migrations/20190728221432-create-role.js
  config/db/migrations/20190729144905-create-blacklistedToken.js
  package-lock.json
  package.json
  src/models/ArticleCategories.js
  src/models/BlacklistedTokens.js
  src/models/Categories.js
  src/models/articles.js
  src/models/authors.js
  src/models/bookmarks.js
  src/models/comments.js
  src/models/downVotes.js
  src/models/followers.js
  src/models/index.js
  src/models/notifications.js
  src/models/permissions.js
  src/models/readStat.js
  src/models/reports.js
  src/models/roles.js
  src/models/upVotes.js
  src/models/user.js
  src/models/users.js
  src/sequelize.js
Labels: ready-for-review

#15 #167377534: Send JWT to user on successful signup and sign-in
  .babelrc
  .env.example
  .nycrc
  app.json
  config/db/migrations/20190728220710-create-users.js
  config/db/migrations/20190728220728-create-articles.js
  config/db/migrations/20190728220750-create-articleCategories.js
  config/db/migrations/20190728220928-create-bookmarks.js
  config/db/migrations/20190728220944-create-categories.js
  config/db/migrations/20190728221000-create-comments.js
  config/db/migrations/20190728221104-create-votes.js
  config/db/migrations/20190728221209-create-followers.js
  config/db/migrations/20190728221239-create-notifications.js
  config/db/migrations/20190728221340-create-readStats.js
  config/db/migrations/20190728221410-create-reports.js
  config/db/migrations/20190728221432-create-roles.js
  config/db/migrations/20190729144905-create-blacklistedTokens.js
  config/db/migrations/20190731080910-create-roles.js
  config/db/seeders/20190731032821-demo-user.js
  config/db/seeders/20190731032821-user-article.js
  package-lock.json
  package.json
  src/controllers/userController.js
  src/helpers/userHelper.js
  src/models/ArticleCategories.js
  src/models/BlacklistedTokens.js
  src/models/Categories.js
  src/models/articles.js
  src/models/bookmarks.js
  src/models/comments.js
  src/models/followers.js
  src/models/index.js
  src/models/notifications.js
  src/models/readStat.js
  src/models/reports.js
  src/models/roles.js
  src/models/users.js
  src/models/votes.js
  src/routes/auth.js
  src/routes/index.js
  src/services/userAuth.js
  tests/mock.js
  tests/test.js
  tests/user.test.js
Labels: ready-for-review
